apiVersion: v1
kind: Service
metadata: { name: incidents-backend }
spec:
  selector: { app: incidents-backend }   # nao bate certo com o label do Deployment (ver deployment.yaml)
  ports: [{ port: 80, targetPort: 8080 }]
